name: Multi-Platform Build

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: '23'

jobs:
  build-jar:
    name: Build JAR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build stripped jar
        run: |
          ./gradlew proguardJar
          mv build/libs/vd-tool-min.jar vd-tool.jar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: vd-tool.jar
          path: vd-tool.jar

  build-native:
    name: Build native binaries
    needs: build-jar
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04-arm
            os: linux
            arch: arm64
          - runner: ubuntu-latest
            os: linux
            arch: x86_64
          - runner: macos-latest
            os: macos
            arch: arm64
          - runner: macos-13
            os: macos
            arch: x86_64
    env:
      FILE_NAME: vd-tool-${{ matrix.os }}-${{ matrix.arch }}

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: vd-tool.jar

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native image
        run: |
          native-image -Os -jar vd-tool.jar ${{ env.FILE_NAME }}

      - name: Compress with UPX
        if: ${{ matrix.os == 'linux' }}
        uses: svenstaro/upx-action@v2
        with:
          strip: 'false'
          file: ${{ env.FILE_NAME }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE_NAME }}
          path: ${{ env.FILE_NAME }}

  release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    name: Create Release
    needs: [ build-native ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          draft: false
          files: release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
